// examples/confirm-close.flow.tsx
import React from "react";

import {
  JOURNEY_TERMINAL,
  type JourneyReactDefinition,
  useJourney,
  JourneyProvider,
  JourneyStepRenderer
} from "../src";

type StepId = "edit" | "confirmExit";
type Ctx = { dirty: boolean };

const Edit = () => {
  const { api } = useJourney<Ctx, StepId>();
  return (
    <div>
      <button onClick={() => api.updateContext((ctx) => ({ ...ctx, dirty: true }))}>
        Make dirty
      </button>
      <button onClick={() => api.close()}>Close</button>
    </div>
  );
};

const ConfirmClose = () => {
  const { api } = useJourney<Ctx, StepId>();
  return <button onClick={() => api.close()}>Confirm close</button>;
};

export const confirmExitJourney: JourneyReactDefinition<Ctx, StepId> = {
  initial: "edit",
  context: { dirty: false },
  steps: {
    edit: { component: Edit },
    confirmExit: { component: ConfirmClose }
  },
  transitions: [
    {
      from: "*",
      event: "close",
      to: "confirmExit",
      when: ({ context }) => context.dirty
    },
    {
      from: "*",
      event: "close",
      to: JOURNEY_TERMINAL.CLOSE,
      when: ({ context }) => !context.dirty
    }
  ]
};

export const ConfirmCloseExample = () => (
  <JourneyProvider journey={confirmExitJourney}>
    <JourneyStepRenderer<Ctx, StepId> />
  </JourneyProvider>
);

// packages/vue/examples/confirm-close.flow.tsx
import { defineComponent } from "vue";

import { createJourneyBindings, type JourneyVueDefinition } from "@rxova/journey-vue";

type StepId = "edit" | "confirmExit";
type Event = "requestClose";
type Ctx = { dirty: boolean };

const Edit = defineComponent({
  setup() {
    const snapshot = bindings.useJourneySnapshot();
    const api = bindings.useJourneyApi();
    const makeDirty = () => api.updateContext((ctx) => ({ ...ctx, dirty: true }));
    const close = () => {
      if (snapshot.value.context.dirty) {
        void api.send({ type: "requestClose" });
        return;
      }
      void api.terminateJourney();
    };
    return { makeDirty, close };
  },
  template: `<div><button @click="makeDirty">Make dirty</button><button @click="close">Close</button></div>`
});

const ConfirmExit = defineComponent({
  setup() {
    const api = bindings.useJourneyApi();
    const onClick = () => void api.terminateJourney();
    return { onClick };
  },
  template: `<button @click="onClick">Confirm close</button>`
});

export const confirmExitJourney: JourneyVueDefinition<Ctx, StepId, Event> = {
  initial: "edit",
  context: { dirty: false },
  steps: {
    edit: { component: Edit },
    confirmExit: { component: ConfirmExit }
  },
  transitions: [
    {
      from: "*",
      event: "requestClose",
      to: "confirmExit",
      when: ({ context }) => context.dirty
    },
    { from: "*", event: "terminateJourney" }
  ]
};

const bindings = createJourneyBindings(confirmExitJourney);

export const ConfirmExitExample = defineComponent({
  components: { Provider: bindings.Provider, StepRenderer: bindings.StepRenderer },
  template: `<Provider><StepRenderer /></Provider>`
});
