// examples/simple-back.flow.tsx
import React from "react";

import {
  HISTORY_TARGET,
  type JourneyReactDefinition,
  useJourney,
  JourneyProvider,
  JourneyStepRenderer
} from "../src";

type StepId = "one" | "two" | "three";
type Ctx = Record<string, never>;

const One = () => {
  const { api } = useJourney<Ctx, StepId>();
  return <button onClick={() => api.next()}>Go</button>;
};

const Two = () => {
  const { api } = useJourney<Ctx, StepId>();
  return (
    <div>
      <button onClick={() => api.back()}>Back</button>
      <button onClick={() => api.next()}>Next</button>
    </div>
  );
};

const Three = () => {
  const { api } = useJourney<Ctx, StepId>();
  return <button onClick={() => api.back()}>Back</button>;
};

export const simpleBackJourney: JourneyReactDefinition<Ctx, StepId> = {
  initial: "one",
  context: {},
  steps: {
    one: { component: One },
    two: { component: Two },
    three: { component: Three }
  },
  transitions: [
    { from: "one", event: "next", to: "two" },
    { from: "two", event: "next", to: "three" },
    { from: "*", event: "back", to: HISTORY_TARGET }
  ]
};

export const SimpleBackJourneyExample = () => (
  <JourneyProvider journey={simpleBackJourney}>
    <JourneyStepRenderer<Ctx, StepId> />
  </JourneyProvider>
);

// packages/vue/examples/simple-back.flow.tsx
import { defineComponent } from "vue";

import { createJourneyBindings, type JourneyVueDefinition } from "@rxova/journey-vue";

type StepId = "one" | "two" | "three";
type Ctx = Record<string, never>;

const One = defineComponent({
  setup() {
    const api = bindings.useJourneyApi();
    const onClick = () => void api.goToNextStep();
    return { onClick };
  },
  template: `<button @click="onClick">Go</button>`
});

const Two = defineComponent({
  setup() {
    const api = bindings.useJourneyApi();
    const onBack = () => void api.goToPreviousStep();
    const onNext = () => void api.goToNextStep();
    return { onBack, onNext };
  },
  template: `<div><button @click="onBack">Back</button><button @click="onNext">Next</button></div>`
});

const Three = defineComponent({
  setup() {
    const api = bindings.useJourneyApi();
    const onClick = () => void api.goToPreviousStep();
    return { onClick };
  },
  template: `<button @click="onClick">Back</button>`
});

export const simpleBackJourney: JourneyVueDefinition<Ctx, StepId> = {
  initial: "one",
  context: {},
  steps: {
    one: { component: One },
    two: { component: Two },
    three: { component: Three }
  },
  transitions: [
    { from: "one", event: "goToNextStep", to: "two" },
    { from: "two", event: "goToNextStep", to: "three" }
  ]
};

const bindings = createJourneyBindings(simpleBackJourney);

export const SimpleBackJourneyExample = defineComponent({
  components: { Provider: bindings.Provider, StepRenderer: bindings.StepRenderer },
  template: `<Provider><StepRenderer /></Provider>`
});
