// packages/vue/examples/simple-sequence.flow.tsx
import { defineComponent } from "vue";

import { createJourneyBindings, type JourneyVueDefinition } from "@rxova/journey-vue";

type StepId = "s1" | "s2";
type Ctx = Record<string, never>;

const S1 = defineComponent({
  setup() {
    const api = bindings.useJourneyApi();
    const onClick = () => void api.goToNextStep();
    return { onClick };
  },
  template: `<button @click="onClick">Continue</button>`
});

const S2 = defineComponent({
  setup() {
    const api = bindings.useJourneyApi();
    const onClick = () => void api.completeJourney();
    return { onClick };
  },
  template: `<button @click="onClick">Done</button>`
});

export const simpleSequenceJourney: JourneyVueDefinition<Ctx, StepId> = {
  initial: "s1",
  context: {},
  steps: {
    s1: { component: S1 },
    s2: { component: S2 }
  },
  transitions: [
    { from: "s1", event: "goToNextStep", to: "s2" },
    { from: "s2", event: "completeJourney" }
  ]
};

const bindings = createJourneyBindings(simpleSequenceJourney);

export const SimpleSequenceJourneyExample = defineComponent({
  components: { Provider: bindings.Provider, StepRenderer: bindings.StepRenderer },
  template: `<Provider><StepRenderer /></Provider>`
});

// examples/simple-sequence.flow.tsx
import React from "react";

import {
  JOURNEY_TERMINAL,
  type JourneyReactDefinition,
  useJourney,
  JourneyProvider,
  JourneyStepRenderer
} from "../src";

type StepId = "s1" | "s2";
type Ctx = Record<string, never>;

const S1 = () => {
  const { api } = useJourney<Ctx, StepId>();
  return <button onClick={() => api.next()}>Continue</button>;
};

const S2 = () => {
  const { api } = useJourney<Ctx, StepId>();
  return <button onClick={() => api.submit()}>Done</button>;
};

export const simpleSequenceJourney: JourneyReactDefinition<Ctx, StepId> = {
  initial: "s1",
  context: {},
  steps: {
    s1: { component: S1 },
    s2: { component: S2 }
  },
  transitions: [
    { from: "s1", event: "next", to: "s2" },
    { from: "s2", event: "submit", to: JOURNEY_TERMINAL.COMPLETE }
  ]
};

export const SimpleSequenceJourneyExample = () => (
  <JourneyProvider journey={simpleSequenceJourney}>
    <JourneyStepRenderer<Ctx, StepId> />
  </JourneyProvider>
);
