// packages/vue/examples/support-ticket.flow.tsx
import { defineComponent } from "vue";

import { createJourneyBindings, type JourneyVueDefinition } from "@rxova/journey-vue";

type StepId = "category" | "details" | "screenshot" | "review" | "confirmExit";
type Event = "requestClose";
type Ctx = {
  includeScreenshot: boolean;
  dirty: boolean;
};

const Category = defineComponent({
  setup() {
    const api = bindings.useJourneyApi();
    const onClick = () => void api.goToNextStep();
    return { onClick };
  },
  template: `<button @click="onClick">Continue</button>`
});

const Details = defineComponent({
  setup() {
    const api = bindings.useJourneyApi();
    const onClick = () => void api.goToNextStep();
    return { onClick };
  },
  template: `<button @click="onClick">Continue</button>`
});

const Screenshot = defineComponent({
  setup() {
    const api = bindings.useJourneyApi();
    const onClick = () => void api.goToNextStep();
    return { onClick };
  },
  template: `<button @click="onClick">Continue</button>`
});

const Review = defineComponent({
  setup() {
    const api = bindings.useJourneyApi();
    const onClick = () => void api.completeJourney();
    return { onClick };
  },
  template: `<button @click="onClick">Submit</button>`
});

const ConfirmExit = defineComponent({
  setup() {
    const api = bindings.useJourneyApi();
    const onClick = () => void api.terminateJourney();
    return { onClick };
  },
  template: `<button @click="onClick">Discard</button>`
});

export const supportTicketJourney: JourneyVueDefinition<Ctx, StepId, Event> = {
  initial: "category",
  context: {
    includeScreenshot: false,
    dirty: false
  },
  steps: {
    category: { component: Category },
    details: { component: Details },
    screenshot: { component: Screenshot },
    review: { component: Review },
    confirmExit: { component: ConfirmExit }
  },
  transitions: [
    { from: "category", event: "goToNextStep", to: "details" },
    {
      from: "details",
      event: "goToNextStep",
      to: "screenshot",
      when: ({ context }) => context.includeScreenshot
    },
    {
      from: "details",
      event: "goToNextStep",
      to: "review",
      when: ({ context }) => !context.includeScreenshot
    },
    { from: "screenshot", event: "goToNextStep", to: "review" },
    {
      from: "*",
      event: "requestClose",
      to: "confirmExit",
      when: ({ context }) => context.dirty
    },
    { from: "*", event: "terminateJourney" },
    { from: "review", event: "completeJourney" }
  ]
};

const bindings = createJourneyBindings(supportTicketJourney);

export const SupportTicketExample = defineComponent({
  components: { Provider: bindings.Provider, StepRenderer: bindings.StepRenderer },
  template: `<Provider><StepRenderer /></Provider>`
});

// examples/support-ticket.flow.tsx
import React from "react";

import {
  HISTORY_TARGET,
  JOURNEY_TERMINAL,
  type JourneyReactDefinition,
  useJourney,
  JourneyProvider,
  JourneyStepRenderer
} from "@/src";

type StepId = "category" | "details" | "screenshot" | "review" | "confirmExit";
type Ctx = {
  includeScreenshot: boolean;
  dirty: boolean;
};

const Category = () => {
  const { api } = useJourney<Ctx, StepId, never>();
  return <button onClick={() => api.next()}>Continue</button>;
};

const Details = () => {
  const { api } = useJourney<Ctx, StepId, never>();
  return <button onClick={() => api.next()}>Continue</button>;
};

const Screenshot = () => {
  const { api } = useJourney<Ctx, StepId, never>();
  return <button onClick={() => api.next()}>Continue</button>;
};

const Review = () => {
  const { api } = useJourney<Ctx, StepId, never>();
  return <button onClick={() => api.submit()}>Submit</button>;
};

const ConfirmClose = () => {
  const { api } = useJourney<Ctx, StepId, never>();
  return <button onClick={() => api.close()}>Discard</button>;
};

export const supportTicketJourney: JourneyReactDefinition<Ctx, StepId, never> = {
  initial: "category",
  context: {
    includeScreenshot: false,
    dirty: false
  },
  steps: {
    category: { component: Category },
    details: { component: Details },
    screenshot: { component: Screenshot },
    review: { component: Review },
    confirmExit: { component: ConfirmClose }
  },
  transitions: [
    { from: "category", event: "next", to: "details" },
    {
      from: "details",
      event: "next",
      to: "screenshot",
      when: ({ context }) => context.includeScreenshot
    },
    {
      from: "details",
      event: "next",
      to: "review",
      when: ({ context }) => !context.includeScreenshot
    },
    { from: "screenshot", event: "next", to: "review" },
    { from: "*", event: "back", to: HISTORY_TARGET },
    {
      from: "*",
      event: "close",
      to: "confirmExit",
      when: ({ context }) => context.dirty
    },
    {
      from: "*",
      event: "close",
      to: JOURNEY_TERMINAL.CLOSE,
      when: ({ context }) => !context.dirty
    },
    { from: "review", event: "submit", to: JOURNEY_TERMINAL.COMPLETE }
  ]
};

export const SupportTicketExample = () => (
  <JourneyProvider journey={supportTicketJourney}>
    <JourneyStepRenderer<Ctx, StepId> />
  </JourneyProvider>
);
